### ISSUE TITLE
Consider having only one yarn command

### ISSUE THREAD

**Issue by decentralion** [sourcecred/template-instance#6]
Right now, we alias the sourcecred commands into package.json, so that we have `yarn score`, `yarn load`, etc.
This has the side-effect that when we add or rename commands, we need to update the package.json. This is fine for updating one repo, but once dozens of people have forked the template, we won't have a way to propagate these changes upstream. So troubleshooting / giving tech support to users will be a pain, since they will not all have the same commands in scope.

Therefore, I think we should consider switching to a single yarn command -- `yarn sc` which is an alias for `yarn sourcecred`. Then users can write `yarn sc load`, `yarn sc score`, etc. It's only three extra characters, and it gives us the ability to upgrade everyone into consistent states just by changing the sourcecred command, without needing to try to encourage everyone to upgrade their package.json.

What do you think @hammadj @topocount @wchargin?

**Comment by topocount** [comment]
I think this makes sense from a maintainability standpoint, and it doesn't really put more of a learning curve on users (instance maintainers specfically) as long as its use is outlined in the readme. 

One thing I've been meaning to bring up: we probably want to improve the `--help` dialogs for each command as well. This seems like a good opportunity to see where this fits in  to this change, since we're pushing users to engage more freely to the CLI.

**Comment by decentralion** [comment]
Yeah, we definitely need to add help info for the CLI.

**Comment by topocount** [comment]
resolved in #22
